name: frontend-ci

on:
  push:
    branches: [ main, feature/** ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"

permissions:
  contents: read

jobs:
  install-lint-test-build:
    runs-on: ubuntu-latest
    if: hashFiles('frontend/package.json') != ''
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Unit test (optional)
        run: npm test --if-present -- --ci

      - name: Build
        run: npm run build

  skip-frontend:
    runs-on: ubuntu-latest
    if: hashFiles('frontend/package.json') == ''
    steps:
      - run: echo "No frontend/package.json. Skipping frontend CI."
